apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: dev
  # labels:
  #   app: kibana
  # # annotations:
  #  konghq.com/strip-path: "false"
  # #  konghq.com/plugins: grade-auth, grade-ratelimit   # Plugin names referenced in KongPlugin resources
  #  kubernetes.io/ingress.class: kong
  #  konghq.com/methods: "GET, POST"  
spec:
  # ingressClassName: kong
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /kibana
        backend:
          service:
            name: kibana
            port: 
              number: 5601
