apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: test
spec:
  # type: NodePort
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: nginx-test
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 32000
